### PR TITLE
Fix grammar

### PR DESCRIPTION
**Pull request by pjackson3**
Just from the first glance, I noticed that this needed significant grammar changes for readability. I used Grammarly to fix it.

### CODE REVIEW

**Comment by PaperPrototype** [comment]
@pjackson3 the pull request contains technical errors. Like when I mention the file DataDefs.cs it removes the “s” making the file name be “DataDefs.c” which is not correct.

**Comment by PaperPrototype** [comment]
I’d rather sacrifice on some grammar over errors :/

But the grammar does need fixed. I will try to go over the pull request and fixe them later. Or maybe you can @pjackson3

**Comment by PaperPrototype** [comment]
Man... I'm reading the comments I made... I came across really rude! Really sorry about that! I really appreciate the pull request! @pjackson3  (It was also probably really late, and we are moving so I was under a lot of stress)

**Comment by PaperPrototype** [comment]
The only problems that need fixed (as far as I know) are grammarly thinking that the "s" at the end of "DataDefs.cs" is there to make the "word" plural. 

So gramarly removed the s making the file ending "DataDefs.c" which is not correct

**Comment by pjackson3** [comment]
I checked, there are no .c files mentioned in there. Only .cs files.

**Comment by pjackson3** [comment]
Only .cs files

**Pull request merged**
